name:                codility
version:             0.1.0.0
github:              "johnf9896/codility_haskell"
license:             BSD3
author:              "Jhon Pedroza"
maintainer:          "jhonfpedroza@gmail.com"
copyright:           "2019 Jhon Pedroza"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/codility#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  codility-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codility

tests:
  codility-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codility
